# -*- coding: utf-8 -*-
"""
Extract per-speaker transcripts from C2 ASR prediction JSON.

Input is the asr_predictions.json generated by c2_asr.py when diarization is enabled.
The script writes:
1. a structured JSON grouped by sample and speaker
2. a readable TXT transcript grouped by sample and speaker
3. an optional script-style TXT transcript ordered by time
"""

from __future__ import annotations

import argparse
import json
import os
from collections import OrderedDict
from typing import Any


def format_time(ms: int) -> str:
    seconds = max(0, int(ms)) / 1000.0
    minutes = int(seconds // 60)
    rest = seconds - minutes * 60
    return f"{minutes:02d}:{rest:06.3f}"


def chunk_overlap_ratio(chunk: dict[str, Any]) -> float:
    duration_s = max(0.001, (int(chunk.get("end_ms", 0)) - int(chunk.get("start_ms", 0))) / 1000.0)
    return float(chunk.get("speaker_overlap_s") or 0.0) / duration_s


def should_keep_chunk(chunk: dict[str, Any], min_overlap_s: float, min_overlap_ratio: float) -> bool:
    text = str(chunk.get("text") or "").strip()
    if not text:
        return False
    overlap_s = float(chunk.get("speaker_overlap_s") or 0.0)
    if overlap_s < min_overlap_s:
        return False
    if chunk_overlap_ratio(chunk) < min_overlap_ratio:
        return False
    return True


def extract_sample(
    sample: dict[str, Any],
    min_overlap_s: float = 0.0,
    min_overlap_ratio: float = 0.0,
    unknown_speaker: str = "UNKNOWN",
) -> dict[str, Any]:
    speakers: OrderedDict[str, dict[str, Any]] = OrderedDict()

    for chunk in sorted(sample.get("chunks", []), key=lambda row: int(row.get("start_ms", 0))):
        if not should_keep_chunk(chunk, min_overlap_s, min_overlap_ratio):
            continue

        speaker = str(chunk.get("speaker") or unknown_speaker)
        speaker_row = speakers.setdefault(
            speaker,
            {
                "text": "",
                "duration_ms": 0,
                "utterances": [],
            },
        )

        utterance = {
            "chunk_id": chunk.get("chunk_id"),
            "start_ms": int(chunk.get("start_ms", 0)),
            "end_ms": int(chunk.get("end_ms", 0)),
            "start": format_time(int(chunk.get("start_ms", 0))),
            "end": format_time(int(chunk.get("end_ms", 0))),
            "text": str(chunk.get("text") or "").strip(),
            "speaker_overlap_s": round(float(chunk.get("speaker_overlap_s") or 0.0), 3),
            "speaker_overlap_ratio": round(chunk_overlap_ratio(chunk), 3),
        }
        speaker_row["utterances"].append(utterance)
        speaker_row["duration_ms"] += utterance["end_ms"] - utterance["start_ms"]

    for speaker_row in speakers.values():
        speaker_row["text"] = " ".join(row["text"] for row in speaker_row["utterances"]).strip()
        speaker_row["duration_s"] = round(speaker_row.pop("duration_ms") / 1000.0, 3)

    return {
        "id": sample.get("id"),
        "audio": sample.get("audio"),
        "num_speakers": len(speakers),
        "speakers": speakers,
    }


def extract_predictions(
    predictions: list[dict[str, Any]],
    min_overlap_s: float = 0.0,
    min_overlap_ratio: float = 0.0,
    unknown_speaker: str = "UNKNOWN",
) -> list[dict[str, Any]]:
    return [
        extract_sample(
            sample,
            min_overlap_s=min_overlap_s,
            min_overlap_ratio=min_overlap_ratio,
            unknown_speaker=unknown_speaker,
        )
        for sample in predictions
    ]


def write_text_report(rows: list[dict[str, Any]], output_path: str) -> None:
    with open(output_path, "w", encoding="utf-8") as f:
        for sample in rows:
            f.write(f"# {sample.get('id')}\n")
            if sample.get("audio"):
                f.write(f"audio: {sample['audio']}\n")
            f.write(f"speakers: {sample.get('num_speakers', 0)}\n\n")

            for speaker, speaker_row in sample.get("speakers", {}).items():
                f.write(f"## {speaker}\n")
                f.write(f"duration_s: {speaker_row.get('duration_s', 0)}\n")
                f.write(f"text: {speaker_row.get('text', '')}\n\n")
                for utterance in speaker_row.get("utterances", []):
                    f.write(
                        f"[{utterance['start']} - {utterance['end']}] "
                        f"chunk={utterance['chunk_id']} "
                        f"overlap={utterance['speaker_overlap_s']}s "
                        f"ratio={utterance['speaker_overlap_ratio']}: "
                        f"{utterance['text']}\n"
                    )
                f.write("\n")


def iter_time_ordered_utterances(sample: dict[str, Any]) -> list[dict[str, Any]]:
    utterances = []
    for speaker, speaker_row in sample.get("speakers", {}).items():
        for utterance in speaker_row.get("utterances", []):
            row = dict(utterance)
            row["speaker"] = speaker
            utterances.append(row)
    return sorted(utterances, key=lambda row: (int(row.get("start_ms", 0)), int(row.get("end_ms", 0))))


def merge_consecutive_utterances(utterances: list[dict[str, Any]]) -> list[dict[str, Any]]:
    merged = []
    for utterance in utterances:
        speaker = utterance.get("speaker", "UNKNOWN")
        text = str(utterance.get("text") or "").strip()
        if not text:
            continue

        if merged and merged[-1]["speaker"] == speaker:
            merged[-1]["end_ms"] = max(int(merged[-1]["end_ms"]), int(utterance.get("end_ms", 0)))
            merged[-1]["end"] = format_time(merged[-1]["end_ms"])
            merged[-1]["text"] = f"{merged[-1]['text']} {text}".strip()
            merged[-1]["chunk_ids"].append(utterance.get("chunk_id"))
            continue

        merged.append(
            {
                "speaker": speaker,
                "start_ms": int(utterance.get("start_ms", 0)),
                "end_ms": int(utterance.get("end_ms", 0)),
                "start": format_time(int(utterance.get("start_ms", 0))),
                "end": format_time(int(utterance.get("end_ms", 0))),
                "text": text,
                "chunk_ids": [utterance.get("chunk_id")],
            }
        )
    return merged


def write_script_report(rows: list[dict[str, Any]], output_path: str) -> None:
    with open(output_path, "w", encoding="utf-8") as f:
        for sample in rows:
            f.write(f"# {sample.get('id')}\n")
            if sample.get("audio"):
                f.write(f"audio: {sample['audio']}\n")
            f.write(f"speakers: {sample.get('num_speakers', 0)}\n\n")

            utterances = merge_consecutive_utterances(iter_time_ordered_utterances(sample))
            for utterance in utterances:
                f.write(
                    f"[{utterance['start']} - {utterance['end']}] "
                    f"{utterance['speaker']}: {utterance['text']}\n"
                )
            f.write("\n")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Extract per-speaker transcripts from C2 ASR predictions.")
    parser.add_argument("--input", default="/root/siton-tmp/assignment_C/C2_ASR/outputs/c2_vad_asr/ava-v3/asr_predictions.json", help="Path to asr_predictions.json")
    parser.add_argument(
        "--mode",
        default="transcript",
        choices=["transcript", "script"],
        help="transcript groups output by speaker; script orders dialogue by time.",
    )
    parser.add_argument("--out_json", default="/root/siton-tmp/assignment_C/C2_ASR/outputs/c2_vad_asr/ava-v3/speaker_transcripts.json", help="Output JSON path")
    parser.add_argument("--out_txt", default="/root/siton-tmp/assignment_C/C2_ASR/outputs/c2_vad_asr/ava-v3/speaker_transcripts.txt", help="Output readable TXT path")
    parser.add_argument(
        "--min_overlap_s",
        type=float,
        default=0.0,
        help="Drop chunks whose speaker overlap is below this many seconds.",
    )
    parser.add_argument(
        "--min_overlap_ratio",
        type=float,
        default=0.0,
        help="Drop chunks whose speaker overlap ratio is below this value, e.g. 0.3.",
    )
    parser.add_argument("--unknown_speaker", default="UNKNOWN", help="Speaker label for chunks without speaker.")
    return parser


def main() -> None:
    args = build_arg_parser().parse_args()
    input_path = os.path.abspath(args.input)
    base_dir = os.path.dirname(input_path)
    out_json = args.out_json or os.path.join(base_dir, "speaker_transcripts.json")
    default_txt_name = "speaker_transcripts.script.txt" if args.mode == "script" else "speaker_transcripts.txt"
    out_txt = args.out_txt or os.path.join(base_dir, default_txt_name)

    with open(input_path, encoding="utf-8") as f:
        predictions = json.load(f)
    if not isinstance(predictions, list):
        raise ValueError("Input JSON must be a list of prediction rows.")

    rows = extract_predictions(
        predictions,
        min_overlap_s=args.min_overlap_s,
        min_overlap_ratio=args.min_overlap_ratio,
        unknown_speaker=args.unknown_speaker,
    )

    os.makedirs(os.path.dirname(os.path.abspath(out_json)), exist_ok=True)
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(rows, f, ensure_ascii=False, indent=2)
    if args.mode == "script":
        write_script_report(rows, out_txt)
    else:
        write_text_report(rows, out_txt)

    print(f"Saved JSON: {out_json}")
    print(f"Saved TXT: {out_txt}")
    for sample in rows:
        print(f"{sample.get('id')}: {sample.get('num_speakers', 0)} speakers")


if __name__ == "__main__":
    main()
